version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 287870619061.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t docker-website .
      - docker tag docker-website:latest 287870619061.dkr.ecr.us-east-1.amazonaws.com/docker-website-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 287870619061.dkr.ecr.us-east-1.amazonaws.com/docker-website-repo:latest

artifacts:
  files:
    - '**/*'


